# .github/workflows/lint-and-test.yml
name: Lint & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    name: Lint & Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install flake8 & pytest
        run: |
          pip install flake8 pytest

      - name: Install service dependencies
        run: |
          for dir in services/*; do
            if [ -f "$dir/requirements.txt" ]; then
              pip install -r "$dir/requirements.txt"
            fi
          done

      - name: Lint with flake8
        run: |
          flake8 .

#      - name: Run pytest
#        run: |
#          pytest --maxfail=1 --disable-warnings -q